// <auto-generated />
namespace LoginPoC.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_process_documents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_process_documents));
        
        string IMigrationMetadata.Id
        {
            get { return "201710030222030_add_process_documents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
